INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('MAKER') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('CHECKER') ON CONFLICT DO NOTHING;
