spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 537745065567-1d5baugb9j5drluib3q63p6dsth51pgv.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
jwt:
  secret: "b2f7e8c9d1a4e5f6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b2f7e8c9d1a4e5f6b7c8d9e0f1a2b3c4"
  expiration: 86400000 # 1 day in ms
  refreshExpiration: 604800000 # 7 days in ms
